### ISSUE TITLE
Can i make a forge port of your mod called 'ForgetMeChunk' ?

### ISSUE THREAD

**Issue by AbdElAziz333** [mjwells2002/ForgetMeChunk#12]
Hello, a lot of forge modpacks needs your performance mod called 'ForgetMeChunk', So
can i port it for the forge mod loader and i can credit you as original author.
And don't worry i will not drop the support of it and i accept every condition you ask for.
Also if you have a discord name for easy contact i will be appreciated.

My discord name : AbdElAziz#1914

**Comment by mjwells2002** [comment]
you know i get an email for curseforge messages, and github issues, you dont need to do both, and while yes i cant stop you, i recommend that you wait until i port this mod to 1.19 as there will be some important information coming with that update, if all goes to plan im doing the testing and porting tomorrow

**Comment by mjwells2002** [comment]
But yes, sure you can port it, and as per the license you are allowed to, i imagine it would also be quite easy as this entire mod is one mixin

**Comment by AbdElAziz333** [comment]
Okay i will port it when you create the 1.19 version, sorry for sending messages on both curseforge and github issues, Thank you for the reply!

**Comment by mjwells2002** [comment]
the readme has been updated with as for mentioned important info if you deciede to port this please include that infomantion, this fix is not perfect and is at best a hack
