### ISSUE TITLE
Error when joining server

### ISSUE THREAD

**Issue by boasbakker** [mjwells2002/ForgetMeChunk#13]
![image](https://user-images.githubusercontent.com/59883944/173230171-e7766076-9aff-4a56-8325-627959944f2f.png)
I have installed these mods:

**Comment by boasbakker** [comment]
![image](https://user-images.githubusercontent.com/59883944/173230179-9cd87712-8259-447b-959e-7299b84727c2.png)

**Comment by boasbakker** [comment]
Server log:
`
11:49:32] [User Authenticator #4/INFO]: UUID of player _Boas_ is 0e195094-3422-427a-81b4-d17b34b820cf
[11:49:32] [Server thread/INFO]: _Boas_[/127.0.0.1:55026] logged in with entity id 326 at (10.5, 79.0, 30.5)
[11:49:32] [Server thread/INFO]: _Boas_ joined the game
[11:49:32] [Server thread/INFO]: _Boas_ lost connection: Disconnected
[11:49:32] [Server thread/INFO]: _Boas_ left the game
[11:49:32] [Server thread/WARN]: handleDisconnection() called twice
`
Client log:
`[11:49:02] [Render thread/INFO]: Connecting to localhost, 25565
[11:49:31] [Render thread/INFO]: Disconnect from localhost
[11:49:31] [Render thread/INFO]: Connecting to localhost, 25565`

**Comment by boasbakker** [comment]
It was fixed when I removed the ForgetMeChunk mod

**Comment by henkelmax** [comment]
This mod is client side only, the server will break if you install it there.

**Comment by boasbakker** [comment]
Sorry I said it wrong, the server doesn't have the mod

**Comment by mjwells2002** [comment]
> This mod is client side only, the server will break if you install it there.

it wont it just wont do anything

**Comment by mjwells2002** [comment]
what minecraft version is this? and mod version

**Comment by mjwells2002** [comment]
actually i think i see the problem, your using debugify, it contains the exact same fix as this mod, if it still happens without debugify installed, please re open this

**Comment by mjwells2002** [comment]
i also recommend you read the readme for this mod, the fix used here and in debugify, is at best a hack and causes a memory leak, so make your own choice on if you want to use the mod knowing that it causes a memory leak (read the readme for more context)

**Comment by boasbakker** [comment]
1.19 newest version

**Comment by boasbakker** [comment]
> 

oh yeah I just downloaded it as it said it was a performance mod lol

**Comment by Brittank88** [comment]
Could we please have this mod [categorise Debugify under `breaks`](https://fabricmc.net/wiki/documentation:fabric_mod_json_spec#optional_fields_dependency_resolution)? It took a very long time to figure out that this was the root cause.

Or should I be asking the Debugify devs to implement that instead?
