### ISSUE TITLE
Disconnect on joining any server

### ISSUE THREAD

**Issue by Apprisco** [mjwells2002/ForgetMeChunk#15]
![Uploading image.png…]()
Confirmed to be forgetmechunk, latest ver

**Comment by Apprisco** [comment]
![image](https://user-images.githubusercontent.com/34324909/173893301-576d8c4f-374f-4ae4-9622-6314735fd546.png)

**Comment by mjwells2002** [comment]
https://github.com/mjwells2002/ForgetMeChunk/issues/13
