### ISSUE TITLE
Forge version insted of Fabric version

### ISSUE THREAD

**Issue by NinesChaosu** [mjwells2002/ForgetMeChunk#16]
Every time im installing new fabric version of ForgetMeChunk game says that this version is not compatible with fabric modloader
https://www.curseforge.com/minecraft/mc-mods/forgetmechunk 1.19

**Comment by mjwells2002** [comment]
Oh yea i forgot to tag it like that, so ill update it, but do consider using modrinth rather then curseforge https://modrinth.com/mod/forgetmechunk modrinth are taking a much more open and friendly approach to distributing mods like this
