### ISSUE TITLE
[Bug] No CurseForge

### ISSUE THREAD

**Issue by RaptaG** [mjwells2002/ForgetMeChunk#3]
A CF upload would be very useful, especially for modpack developes

**Comment by mjwells2002** [comment]
this is not a bug i do not like curseforge this may change in the future but not right now

**Comment by mjwells2002** [comment]
actually on second thought i see your point about modpacks i will create a curseforge page

**Comment by mjwells2002** [comment]
https://www.curseforge.com/minecraft/mc-mods/forgetmechunk
