### ISSUE TITLE
Compatibility with Starlight?

### ISSUE THREAD

**Issue by Tempest-5ky** [mjwells2002/ForgetMeChunk#6]
Hello! Just a quick question, as this mod affects chunk lighting and Starlight (https://github.com/PaperMC/Starlight) is a mod that completely rewrites the lighting engine, would there be incompatibilities if both were used at once?
Thank you!

**Comment by mjwells2002** [comment]
read the readme
https://github.com/mjwells2002/ForgetMeChunk#a-note-on-starlight
